module.exports = {
  printWidth: 100,
  tabWidth: 4,
  useTabs: true,
  semi: true,
  singleQuote: true,
  quoteProps: "consistent",
  jsxSingleQuote: true,
  trailingComma: "none",
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  rangeStart: 0,
  rangeEnd: Infinity,
  endOfLine: "auto",
  singleAttributePerLine: true,
  plugins: [],
  pluginSearchDirs: ["."],
  overrides: [],
};
