on:
	push:
	  branches: [ master ]
	pull_request:
	  branches: [ master ]
  
  jobs:
	setup:
	  runs-on: ubuntu-latest
	  outputs:
		cache-key: ${{ steps.cache-keys.outputs.key }}
	  steps:
		- uses: actions/checkout@v2
		- name: Use Node.js 20.x
		  uses: actions/setup-node@v3
		  with:
			node-version: 20.x
		- name: Cache node modules
		  id: cache-keys
		  uses: actions/cache@v2
		  with:
			path: node_modules
			key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
		- name: Install dependencies
		  if: steps.cache-keys.outputs.cache-hit != 'true'
		  run: yarn install
		- name: Save node modules
		  uses: actions/upload-artifact@v2
		  with:
			name: node_modules
			path: node_modules
  
	lint:
	  needs: setup
	  runs-on: ubuntu-latest
	  steps:
		- uses: actions/checkout@v2
		- name: Use Node.js 20.x
		  uses: actions/setup-node@v3
		  with:
			node-version: 20.x
		- name: Download node modules
		  uses: actions/download-artifact@v2
		  with:
			name: node_modules
			path: node_modules
		- name: Lint
		  run: yarn lint
  
	prettier:
	  needs: setup
	  runs-on: ubuntu-latest
	  steps:
		- uses: actions/checkout@v2
		- name: Use Node.js 20.x
		  uses: actions/setup-node@v3
		  with:
			node-version: 20.x
		- name: Download node modules
		  uses: actions/download-artifact@v2
		  with:
			name: node_modules
			path: node_modules
		- name: Prettier
		  run: yarn prettier
  